// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Wb4Lk3UxhnZhkR5th5exw7ukoffqfB0',
    appId: '1:247183638490:web:47152facaca175a0cb8ae3',
    messagingSenderId: '247183638490',
    projectId: 'contacts-app-82dc6',
    authDomain: 'contacts-app-82dc6.firebaseapp.com',
    storageBucket: 'contacts-app-82dc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwyw96s0SkSKBb6LesFZ6OkHZ_-zOKGnM',
    appId: '1:247183638490:android:c4a8a0989d8dfe88cb8ae3',
    messagingSenderId: '247183638490',
    projectId: 'contacts-app-82dc6',
    storageBucket: 'contacts-app-82dc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Ev-gwY76sZNliHJ75eI5twyRdPWZCZY',
    appId: '1:247183638490:ios:18ccfe7535dcdd18cb8ae3',
    messagingSenderId: '247183638490',
    projectId: 'contacts-app-82dc6',
    storageBucket: 'contacts-app-82dc6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Ev-gwY76sZNliHJ75eI5twyRdPWZCZY',
    appId: '1:247183638490:ios:18ccfe7535dcdd18cb8ae3',
    messagingSenderId: '247183638490',
    projectId: 'contacts-app-82dc6',
    storageBucket: 'contacts-app-82dc6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Wb4Lk3UxhnZhkR5th5exw7ukoffqfB0',
    appId: '1:247183638490:web:4357c0ce457bdf8ecb8ae3',
    messagingSenderId: '247183638490',
    projectId: 'contacts-app-82dc6',
    authDomain: 'contacts-app-82dc6.firebaseapp.com',
    storageBucket: 'contacts-app-82dc6.firebasestorage.app',
  );
}
